import { test, expect } from '@playwright/test';

test('organizer can find athletes and assign bibs before and after the start on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/login');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('admin@example.test');
  await page.getByLabel('Password', { exact: true }).fill('browser-test-password-123');
  await page.getByRole('button', { name: /sign in|log in/i }).click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto('/races/create');
  await page.getByPlaceholder('Halle Triathlon 2027').fill('Bib editing');
  await page.getByRole('button', { name: 'Create and continue', exact: true }).click();
  await expect(page).toHaveURL(/\/races\/\d+$/);
  const racePath = new URL(page.url()).pathname;
  await page.getByRole('link', { name: 'Athletes', exact: true }).click();
  await expect(page).toHaveURL(`${racePath}/participants`);
  await page.getByLabel('Name', { exact: true }).fill('Alex');
  await expect(page.getByText(/No existing athlete matches|Matching athletes/)).toBeVisible();
  await page.getByRole('button', { name: 'Add athlete', exact: true }).click();
  await expect(page.getByText('Participant added.', { exact: true })).toBeVisible();
  await page.getByRole('link', { name: 'Edit', exact: true }).click();
  await expect(page).toHaveURL(/\/participants\/\d+\/edit$/);
  await page.getByLabel('Bib number (optional)').fill('007');
  await expect(page.getByLabel('Last name (optional)')).toHaveValue('');
  await page.getByRole('button', { name: 'Save participant', exact: true }).click();
  await expect(page.getByText('Participant updated.', { exact: false })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Bib number (optional)')).toHaveValue('007');
  await page.getByRole('link', { name: 'Race workspace', exact: true }).click();
  await expect(page).toHaveURL(racePath);
  const start = page.getByRole('button', { name: 'Start race', exact: true });
  if (!(await start.isVisible())) await page.locator('#race-day > button').click();
  await start.click();
  await page.getByRole('dialog').getByRole('button', { name: 'Start race', exact: true }).click();
  await expect(page.getByRole('timer')).not.toHaveText('NOT STARTED');
  await page.locator('#participants > button').click();
  await page.locator('#participants').getByRole('link', { name: 'Edit', exact: true }).click();
  await expect(page.getByText('The race has started.', { exact: true })).toBeVisible();
  await page.getByLabel('Bib number (optional)').fill('042');
  await page.getByLabel('Reason for change').fill('Bib corrected at check-in');
  await page.getByRole('button', { name: 'Save participant', exact: true }).click();
  await expect(page.getByText('Participant updated.', { exact: false })).toBeVisible();
  await page.getByText('Change history ·', { exact: false }).click();
  await expect(page.getByText('Bib number: 007 → 042', { exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.goto(`${racePath}/participants`);
  await page.getByRole('textbox', { name: 'Search participants' }).fill('042');
  await expect(page.getByText('#042', { exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Edit', exact: true })).toBeVisible();
});
