import { test, expect, type Page } from '@playwright/test';
async function login(page:Page,role='admin') {await page.goto('/login');await page.getByRole('textbox',{name:'Email',exact:true}).fill(`${role}@example.test`);await page.getByLabel('Password',{exact:true}).fill('browser-test-password-123');await page.getByRole('button',{name:/sign in|log in/i}).click();await expect(page).not.toHaveURL(/\/login/);}
test('offline recovery, account isolation, audited edits, filtered results and frozen clocks',async({page,context})=>{
  await login(page);await page.goto('/races/create');await page.getByPlaceholder('Halle Triathlon 2027').fill('Browser readiness');await page.locator('input[type=date]').fill('2026-09-22');await page.getByRole('button',{name:'Create race',exact:true}).click();await expect(page).toHaveURL(/\/races\/\d+$/);const racePath=new URL(page.url()).pathname;
  await page.getByRole('checkbox',{name:'Test Organizer organizer@example.test'}).check();await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect(page.getByText('Race settings updated.',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Participants',exact:true}).click();await page.getByPlaceholder('First name').fill('Offline');await page.getByPlaceholder('Last name').fill('Runner');await page.getByRole('button',{name:'Add participant',exact:true}).click();await expect(page.getByText('Participant added.',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Edit',exact:true}).click();await page.getByLabel('Bib number (optional)').fill('007');await page.getByLabel('Category',{exact:true}).fill('Open');await page.getByLabel('Reason for change').fill('Bib assigned at registration');await page.getByRole('button',{name:'Save participant'}).click();await expect(page.getByText('Participant updated.',{exact:false})).toBeVisible();
  await page.getByRole('link',{name:'Race control',exact:true}).click();await page.getByRole('button',{name:'Start race',exact:true}).click();await page.getByRole('button',{name:'Confirm start',exact:true}).click();await expect(page.getByRole('timer')).not.toHaveText('NOT STARTED');
  const station=await context.newPage();await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await expect(station.getByRole('button',{name:/#007 Offline Runner Solo athlete TAP/})).toBeEnabled();
  // Simulate a transport outage while keeping HTML reload available to verify IndexedDB recovery.
  await context.route('**/races/*/timings',route=>route.abort());await station.getByRole('button',{name:/#007 Offline Runner Solo athlete TAP/}).click();await expect(station.getByRole('button',{name:'Export pending backup'})).toBeVisible();await station.reload();await expect(station.getByRole('button',{name:'Export pending backup'})).toBeVisible();await expect(station.getByRole('button',{name:/#007 Offline Runner Solo athlete RECORDED/})).toBeDisabled();
  await station.getByRole('button',{name:'Log out',exact:true}).click();await login(station,'organizer');await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await expect(station.getByText('pending timings belong to another account.',{exact:false})).toBeVisible();await expect(station.getByRole('button',{name:'Export pending backup'})).toHaveCount(0);
  await station.goto('/dashboard');await station.getByRole('button',{name:'Log out',exact:true}).click();await login(station);await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await context.unroute('**/races/*/timings');await station.getByRole('button',{name:'Sync pending timings',exact:true}).click();await expect(station.getByRole('button',{name:'Export pending backup'})).toHaveCount(0);await expect(station.getByRole('button',{name:'Undo',exact:true})).toBeVisible();
  await page.goto(`${racePath}/control`);await page.getByRole('button',{name:'Finish race',exact:true}).click();await page.getByRole('button',{name:'Confirm finish',exact:true}).click();await expect(station.getByText('Race finished. The shared clock is stopped.',{exact:false})).toBeVisible({timeout:15000});const final=await station.getByRole('timer').innerText();await station.reload();await expect(station.getByRole('timer')).toHaveText(final);
  await page.goto(`${racePath}/participants`);await page.getByRole('link',{name:'Edit',exact:true}).click();await page.getByLabel('Result status').selectOption('dnf');await page.getByLabel('Reason for change').fill('Withdrew after swim');await page.getByRole('button',{name:'Save participant'}).click();await expect(page.getByText('Participant updated.',{exact:false})).toBeVisible();await page.getByRole('link',{name:'Results',exact:true}).click();await page.getByLabel('Result status').selectOption('DNF');await expect(page.getByRole('cell',{name:'Open · DNF',exact:false})).toBeVisible();
});
