import { test, expect, type Page } from '@playwright/test';
async function login(page:Page,role='admin') {await page.goto('/login');await page.getByRole('textbox',{name:'Email',exact:true}).fill(`${role}@example.test`);await page.getByLabel('Password',{exact:true}).fill('browser-test-password-123');await page.getByRole('button',{name:/sign in|log in/i}).click();await expect(page).not.toHaveURL(/\/login/);}
test('offline recovery, account isolation, audited edits, filtered results and frozen clocks',async({page,context})=>{
  await login(page);await page.goto('/races/create');await page.getByPlaceholder('Halle Triathlon 2027').fill('Browser readiness');await page.locator('input[type=date]').fill('2026-09-22');await page.getByRole('button',{name:'Create race',exact:true}).click();await expect(page).toHaveURL(/\/races\/\d+$/);const racePath=new URL(page.url()).pathname;
  await page.getByRole('checkbox',{name:'Test Organizer organizer@example.test'}).check();await page.getByRole('button',{name:'Save settings',exact:true}).click();await expect(page.getByText('Race settings updated.',{exact:true})).toBeVisible();
  await expect(page.getByText('50 · Finish',{exact:true})).toBeVisible();await expect(page.getByText('Run: 8 km · 44 km total',{exact:true})).toBeVisible();await expect(page.getByText('Bike: 0 km · 1 km total',{exact:true})).toBeVisible();await page.getByLabel('Checkpoint name',{exact:true}).fill('Run 4 km');await page.getByLabel('Order in the race',{exact:true}).fill('45');await page.getByLabel('Sport / leg',{exact:true}).selectOption('run');await page.getByLabel('Distance into this leg (km, optional)',{exact:true}).fill('4');await page.getByRole('button',{name:'Add checkpoint',exact:true}).click();await expect(page.getByText('Checkpoint added.',{exact:true})).toBeVisible();await expect(page.getByText('45 · Run 4 km',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Participants',exact:true}).click();await page.getByPlaceholder('First name').fill('Offline');await page.getByPlaceholder('Last name').fill('Runner');await page.getByRole('button',{name:'Add participant',exact:true}).click();await expect(page.getByText('Participant added.',{exact:true})).toBeVisible();
  await page.getByRole('link',{name:'Edit',exact:true}).click();await expect(page).toHaveURL(/\/participants\/\d+\/edit$/);await page.getByLabel('Bib number (optional)').fill('007');await page.getByLabel('Category',{exact:true}).fill('Open');await page.getByLabel('Reason for change').fill('Bib assigned at registration');await expect(page.getByLabel('Bib number (optional)')).toHaveValue('007');await page.getByRole('button',{name:'Save participant'}).click();await expect(page.getByText('Participant updated.',{exact:false})).toBeVisible();await page.reload();await expect(page.getByLabel('Bib number (optional)')).toHaveValue('007');
  await page.getByRole('link',{name:'Race control',exact:true}).click();await page.getByRole('button',{name:'Start race',exact:true}).click();await page.getByRole('button',{name:'Confirm start',exact:true}).click();await expect(page.getByRole('timer')).not.toHaveText('NOT STARTED');
  const station=await context.newPage();await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await expect(station.getByRole('button',{name:/#007.*Offline Runner.*TAP/})).toBeEnabled();
  // Simulate a transport outage while keeping HTML reload available to verify IndexedDB recovery.
  await context.route('**/races/*/timings',route=>route.abort());await station.getByRole('button',{name:/#007.*Offline Runner.*TAP/}).click();await expect(station.getByRole('button',{name:'Export pending backup'})).toBeVisible();await station.reload();await expect(station.getByRole('button',{name:'Export pending backup'})).toBeVisible();await expect(station.getByRole('button',{name:/#007.*Offline Runner.*RECORDED/})).toBeDisabled();
  await station.getByRole('button',{name:'Log out',exact:true}).click();await login(station,'organizer');await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await expect(station.getByText('pending timings belong to another account.',{exact:false})).toBeVisible();await expect(station.getByRole('button',{name:'Export pending backup'})).toHaveCount(0);
  await station.goto('/dashboard');await station.getByRole('button',{name:'Log out',exact:true}).click();await login(station);await station.goto(`${racePath}/station`);await station.getByRole('button',{name:'Start checkpoint mode'}).click();await context.unroute('**/races/*/timings');await station.getByRole('button',{name:'Upload now',exact:true}).click();await expect(station.getByRole('button',{name:'Export pending backup'})).toHaveCount(0);await expect(station.getByRole('button',{name:'Undo',exact:true})).toBeVisible();
  await page.goto(`${racePath}/control`);await page.getByRole('button',{name:'Finish race',exact:true}).click();await page.getByRole('button',{name:'Confirm finish',exact:true}).click();await expect(station.getByText('Race finished. The shared clock is stopped.',{exact:false})).toBeVisible({timeout:15000});const final=await station.getByRole('timer').innerText();await station.reload();await expect(station.getByRole('timer')).toHaveText(final);
  await page.goto(`${racePath}/participants`);await page.getByRole('link',{name:'Edit',exact:true}).click();await expect(page).toHaveURL(/\/participants\/\d+\/edit$/);await page.getByLabel('Result status').selectOption('dnf');await page.getByLabel('Reason for change').fill('Withdrew after swim');await page.getByRole('button',{name:'Save participant'}).click();await expect(page.getByText('Participant updated.',{exact:false})).toBeVisible();await page.getByRole('link',{name:'Results',exact:true}).click();await page.getByLabel('Result status').selectOption('DNF');await expect(page.getByRole('cell',{name:'Open · DNF',exact:false})).toBeVisible();
  await page.getByRole('button',{name:'View splits',exact:true}).click();await expect(page.getByText(/^split \d{2}:\d{2}:\d{2}\.\d{2}$/)).toBeVisible();await page.getByLabel('Timing precision').selectOption('3');await expect(page.getByText(/^split \d{2}:\d{2}:\d{2}\.\d{3}$/)).toBeVisible();
  await page.getByRole('link',{name:'Race control',exact:true}).click();
  await page.getByLabel('Seconds',{exact:true}).fill('4');await page.getByLabel('Milliseconds',{exact:true}).fill('321');await page.getByLabel('Reason for correction').fill('Finish camera review');await page.getByRole('button',{name:'Review correction',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('00:00:04.321');await page.getByRole('button',{name:'Save correction',exact:true}).click();await expect(page.getByText('Checkpoint timing corrected.',{exact:false})).toBeVisible();
  await page.getByRole('link',{name:'Overview & setup',exact:true}).click();await page.getByRole('button',{name:'Publish leaderboard',exact:true}).click();await page.getByRole('button',{name:'Publish results',exact:true}).click();await expect(page.getByRole('link',{name:'Open public leaderboard',exact:false})).toBeVisible();
  const publicPath=await page.getByRole('link',{name:'Open public leaderboard',exact:false}).getAttribute('href');const guestContext=await page.context().browser()!.newContext();const spectator=await guestContext.newPage();await spectator.goto(new URL(publicPath!,page.url()).toString());
  await expect(spectator.getByRole('cell',{name:'Offline Runner',exact:false})).toBeVisible();await expect(spectator.getByRole('link',{name:'Race control',exact:true})).toHaveCount(0);await expect(spectator.getByRole('link',{name:'Export CSV'})).toHaveCount(0);await spectator.getByRole('button',{name:'Large-screen display'}).click();await expect(spectator.getByText('Page 1 of 1',{exact:true})).toBeVisible();await spectator.getByRole('button',{name:'Exit display mode'}).click();
  await page.getByRole('button',{name:'Unpublish leaderboard',exact:true}).click();await page.getByRole('button',{name:'Unpublish',exact:true}).click();await expect(page.getByText('Public leaderboard unpublished.',{exact:false})).toBeVisible();await spectator.reload();await expect(spectator.getByRole('heading',{name:'404',exact:true})).toBeVisible();await guestContext.close();

});
