<script setup lang="ts">
import { usePermissions } from '../../Composables/usePermissions';
const can=usePermissions();
import { Head, Link, router } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
import RaceClock from '../../Components/RaceClock.vue';
import { useRaceRefresh } from '../../Composables/useRaceRefresh';
import { formatDate } from '../../presentation';
import type { Race } from '../../types';
defineProps<{races:Race[];deletedRaces:Race[];serverNow:string}>();
useRaceRefresh(()=>['races','serverNow']);
</script>
<template><Head title="Races"/><AppLayout title="Your races"><div class="mb-5 flex flex-wrap items-center justify-between gap-3"><p class="muted">Set up an event, run your timing station, or review a completed race.</p><Link v-if="can('races.create')" href="/races/create" class="btn-primary"><i class="fa-solid fa-plus" aria-hidden="true"></i>Create race</Link></div><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3"><article v-for="race in races" :key="race.id" class="panel-pad flex flex-col gap-4"><div><span class="badge" :data-status="race.status">{{ race.status }}</span><h2 class="mt-3 text-xl font-bold">{{ race.name }}</h2><p class="mt-1 text-sm muted">{{ formatDate(race.event_date) }} · {{ race.entries_count??0 }} entries</p></div><RaceClock v-if="race.started_at" :started-at="race.started_at" :finished-at="race.finished_at" :server-now="serverNow" compact/><Link :href="race.finished_at?`/races/${race.id}/results`:race.started_at && can('timings.record')?`/races/${race.id}/station`:`/races/${race.id}`" class="btn-primary mt-auto"><i :class="race.finished_at?'fa-solid fa-trophy':race.started_at && can('timings.record')?'fa-solid fa-stopwatch':'fa-solid fa-eye'" aria-hidden="true"></i>{{ race.finished_at?'View results':race.started_at && can('timings.record')?'Open timing station':'View race' }}</Link><div class="grid grid-cols-2 gap-2"><Link :href="`/races/${race.id}`" class="btn-secondary"><i class="fa-solid fa-gear" aria-hidden="true"></i>Overview & setup</Link><Link v-if="can('races.control')" :href="`/races/${race.id}/control`" class="btn-secondary"><i class="fa-solid fa-sliders" aria-hidden="true"></i>Race control</Link></div></article></div><section v-if="!races.length" class="panel-pad text-center"><h2 class="text-xl font-bold">Your first race starts here</h2><p class="mx-auto mt-3 max-w-lg muted">An organizer (admin) can assign you to a race. If your role allows it, you can also create one here.</p><Link v-if="can('races.create')" href="/races/create" class="btn-primary mt-5"><i class="fa-solid fa-plus" aria-hidden="true"></i>Set up your first race</Link></section><details v-if="deletedRaces.length" class="panel-pad mt-6"><summary class="font-bold">Deleted races · {{ deletedRaces.length }}</summary><p class="mt-2 text-sm muted">Restore a race with its participants, timings and assignments.</p><div v-for="race in deletedRaces" :key="race.id" class="flex flex-wrap items-center justify-between gap-3 border-b border-outline py-4 last:border-0"><div><h3 class="font-semibold">{{ race.name }}</h3><p class="text-sm muted">{{ formatDate(race.event_date) }}</p></div><button class="btn-secondary" @click="router.post(`/races/${race.id}/restore`)"><i class="fa-solid fa-rotate-left" aria-hidden="true"></i>Restore race</button></div></details></AppLayout></template>
