<script setup lang="ts">
import { Head, Link } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
import RaceClock from '../../Components/RaceClock.vue';
import { formatDuration } from '../../lib';
interface Athlete { id:number; full_name:string; first_name:string; last_name:string }
interface Timing { id:number; elapsed_ms:number; checkpoint:{id:number;name:string;discipline?:string;kind:string;sequence:number} }
interface Member { id:number; discipline:string; athlete:Athlete }
interface Entry { id:number; bib_number:string; type:string; team_name?:string; race:{id:number;name:string;event_date:string;status:string;started_at?:string|null;finished_at?:string|null}; members:Member[]; timings:Timing[] }
defineProps<{ athlete:Athlete; entries:Entry[]; serverNow:string }>();
</script>
<template><Head title="My race"/><AppLayout :title="`Welcome, ${athlete.first_name}`"><div v-if="entries.length" class="space-y-5"><section v-for="entry in entries" :key="entry.id" class="panel-pad"><div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><span class="badge">{{ entry.race.status }}</span><h2 class="mt-2 text-xl font-bold">{{ entry.race.name }}</h2><div class="muted">{{ entry.race.event_date }} · Bib #{{ entry.bib_number }}</div><div v-if="entry.type==='relay'" class="mt-3 rounded-xl bg-slate-950 p-3"><div class="text-xs font-semibold uppercase tracking-wider text-slate-400">Your team</div><div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm"><span v-for="member in entry.members" :key="member.id"><strong class="capitalize">{{ member.discipline }}:</strong> {{ member.athlete.full_name }}</span></div></div></div><div v-if="entry.race.started_at" class="rounded-xl bg-slate-950 p-4"><div class="mb-1 text-xs uppercase tracking-widest text-cyan-300">Race clock</div><RaceClock :started-at="entry.race.started_at" :server-now="serverNow" compact/></div></div><div class="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div v-for="timing in entry.timings" :key="timing.id" class="rounded-xl border border-slate-800 bg-slate-950 p-4"><div class="text-sm muted">{{ timing.checkpoint.name }}</div><div class="mt-1 font-mono text-xl font-bold">{{ formatDuration(timing.elapsed_ms,true) }}</div></div><div v-if="!entry.timings.length" class="rounded-xl border border-slate-800 p-4 muted">No checkpoint times yet.</div></div><Link :href="`/races/${entry.race.id}/results`" class="btn-secondary mt-5">View full results</Link></section></div><div v-else class="panel-pad text-center"><h2 class="text-lg font-bold">No race entry linked yet</h2><p class="mt-2 muted">Ask the race organizer to link this login to your athlete profile.</p></div></AppLayout></template>
