<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { jsonRequest } from '../lib';
interface Athlete {id:number;first_name:string;last_name:string;email?:string|null}
const props=defineProps<{accountId?:number;initial?:Athlete|null}>();
const model=defineModel<number|null>({required:true});
const query=ref('');const rows=ref<Athlete[]>([]);const selected=ref(props.initial??null);const page=ref(1);const last=ref(1);const busy=ref(false);const error=ref('');
async function search(number=1){busy.value=true;error.value='';try{const params=new URLSearchParams({q:query.value,page:String(number)});if(props.accountId)params.set('account_id',String(props.accountId));const {response,data}=await jsonRequest<{data:Athlete[];current_page:number;last_page:number}>(`/users/athletes?${params}`);if(!response.ok)throw new Error();rows.value=data.data;page.value=data.current_page;last.value=data.last_page;}catch{error.value='Could not load athletes. Please try again.';}finally{busy.value=false;}}
function choose(athlete:Athlete){selected.value=athlete;model.value=athlete.id;}
onMounted(()=>search());
</script>
<template><div class="space-y-3"><label for="athlete-search" class="label">Link athlete</label><div class="flex gap-2"><input id="athlete-search" v-model="query" maxlength="100" class="field" placeholder="First name, last name or email" @keydown.enter.prevent="search()"><button type="button" class="btn-secondary" :disabled="busy" @click="search()">Find</button></div><p v-if="selected && model===selected.id" class="text-sm text-accent">Selected: {{ selected.first_name }} {{ selected.last_name }}{{ selected.email ? ` · ${selected.email}` : '' }}</p><p v-else class="text-sm muted">Select an athlete below.</p><p v-if="error" role="alert" class="text-error">{{ error }}</p><ul class="max-h-64 overflow-auto divide-y divide-outline"><li v-for="athlete in rows" :key="athlete.id"><button type="button" class="w-full p-3 text-left hover:bg-raised" :aria-pressed="model===athlete.id" @click="choose(athlete)">{{ athlete.last_name }}, {{ athlete.first_name }}<span class="block text-xs muted">{{ athlete.email }}</span><span v-if="model===athlete.id" class="text-xs text-accent">Selected</span></button></li></ul><p v-if="!busy&&!rows.length" class="muted">No available athletes match.</p><div class="flex items-center gap-2"><button type="button" class="btn-secondary" :disabled="busy||page<=1" @click="search(page-1)">Previous athletes</button><span class="text-xs">{{ page }} / {{ last }}</span><button type="button" class="btn-secondary" :disabled="busy||page>=last" @click="search(page+1)">Next athletes</button></div></div></template>
