<script setup lang="ts">
import { Head, Link, router, useForm } from '@inertiajs/vue3';
import AppLayout from '../../Layouts/AppLayout.vue';
import type { Race } from '../../types';
interface Batch { id:number; token:string; original_name:string; row_count:number; preview:{row_count:number;entry_count:number;solo_count:number;relay_count:number;sample:Array<Record<string,unknown>>;warnings:string[]} }
const props = defineProps<{ race:Race; batch?:Batch }>();
const form = useForm<{file:File|null}>({file:null});
const fileChanged = (event:Event) => { form.file = (event.target as HTMLInputElement).files?.[0] ?? null; };
const preview = () => form.post(`/races/${props.race.id}/participants/import/preview`, { forceFormData:true });
const confirmImport = () => { if (props.batch) router.post(`/races/${props.race.id}/participants/import/${props.batch.id}/confirm`); };
</script>
<template><Head title="Import participants"/><AppLayout :title="`${race.name} · Import participants`"><div class="mb-5"><Link :href="`/races/${race.id}/participants`" class="btn-secondary"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i>Back to participants</Link></div><div class="grid gap-5 lg:grid-cols-2"><form class="panel-pad" @submit.prevent="preview"><h2 class="text-lg font-bold">Upload participant file</h2><p class="mt-2 muted">Supported: XLSX, XLS, ODS, CSV and JSON. Files are previewed and validated before anything is imported.</p><input class="mt-5 block w-full rounded-xl border border-dashed border-outline-strong bg-canvas p-5" aria-label="Participant file" type="file" accept=".xlsx,.xls,.ods,.csv,.json" @change="fileChanged" required><p v-if="form.errors.file" class="mt-2 text-sm text-error">{{ form.errors.file }}</p><div class="mt-4 flex flex-wrap gap-2"><button class="btn-primary" :disabled="!form.file || form.processing"><i class="fa-solid fa-eye" aria-hidden="true"></i>Preview file</button><a href="/participant-import-template.csv" class="btn-secondary"><i class="fa-solid fa-download" aria-hidden="true"></i>Download CSV template</a></div><div class="mt-5 rounded-xl bg-canvas p-4 text-sm text-secondary"><p class="font-semibold">Row format</p><p class="mt-1 muted">Bibs are optional. Solo: one row per athlete with type=solo, first_name and last_name. Relay: three rows with the same team_name and discipline swim, bike or run. When supplied, the bib must match across the relay. For teams with the same name and no bib, add a distinct entry_key for each team.</p></div></form>
<section v-if="batch" class="panel-pad"><div class="flex items-start justify-between gap-4"><div><span class="badge">Preview</span><h2 class="mt-2 text-lg font-bold">{{ batch.original_name }}</h2></div><div class="text-right text-sm muted">{{ batch.preview.row_count }} rows</div></div><div class="mt-4 grid grid-cols-3 gap-2"><div class="rounded-xl bg-canvas p-3 text-center"><div class="text-xl font-bold">{{ batch.preview.entry_count }}</div><div class="muted text-xs">Entries</div></div><div class="rounded-xl bg-canvas p-3 text-center"><div class="text-xl font-bold">{{ batch.preview.solo_count }}</div><div class="muted text-xs">Solo</div></div><div class="rounded-xl bg-canvas p-3 text-center"><div class="text-xl font-bold">{{ batch.preview.relay_count }}</div><div class="muted text-xs">Relay</div></div></div><div v-if="batch.preview.warnings.length" class="mt-4 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4"><div class="font-semibold text-warning">Warnings</div><ul class="mt-2 list-disc pl-5 text-sm text-warning"><li v-for="warning in batch.preview.warnings" :key="warning">{{ warning }}</li></ul></div><div tabindex="0" role="region" aria-label="Import preview rows" class="scroll-region mt-4 max-h-64 overflow-auto rounded-xl border border-outline"><table class="w-full text-left text-xs"><thead class="sticky top-0 bg-surface"><tr><th class="p-2">Bib</th><th class="p-2">Type</th><th class="p-2">Name</th><th class="p-2">Discipline</th></tr></thead><tbody><tr v-for="(row,index) in batch.preview.sample" :key="index" class="border-t border-outline"><td class="p-2">{{ row.bib || '—' }}</td><td class="p-2">{{ row.type ?? 'solo' }}</td><td class="p-2">{{ row.first_name }} {{ row.last_name }}</td><td class="p-2">{{ row.discipline ?? 'all' }}</td></tr></tbody></table></div><button class="btn-primary mt-5 w-full" @click="confirmImport"><i class="fa-solid fa-check" aria-hidden="true"></i>Confirm import</button></section></div></AppLayout></template>
